#+TITLE: TODOs
#+OPTIONS: tex:t
#+OPTIONS: toc:nil
** TODO investigate dynamic objects
*** add visualization: After reconstructing a 3D point P at t_{i+1}, project P in the image at t_{i} and print line connecting it with the 2D feature correspondence from p_{i}
*** \rightarrow the goal is to identify dynamic objects during reconstruction to become more robust to violations of the underlying static scene assumption
** TODO define arrays like indices, points2D and points3D global in MotionEstimation to reduce arguments in functions \rightarrow or maybe save directly in frame class
** TODO clear interface, i.e. delete redundant arrays and refactor classes
** PROBLEM when running on the EuRoC Machine Hall dataset too less features can be robustly detected which leads to inaccurate pose estimations at PnP computation
*** TODO an appropriate solution would be to add a local map which stores already reconstructed 3D points over a longer period. These can additionally used later at the PnP computation
**** the local map could hold 3D points according to a voting scheme: whenever a 3D point was tracked successfully it will be upvoted (e.g. when it has been set as inlier during RANSAC PnP), else it will be downvoted. A less strict version could be, to upvote 3D points whenever they can bee seen by the current frame (can be checked by projecting 3D point into current frame), else downvote. Remove points from the local map when their vote reached zero or below.
** TODO add SFMViz from L_SLAM code for more interactive 3D visualization
